### ISSUE TITLE
Test existing WEB UI

### ISSUE THREAD

**Issue by taobaodog** [taobaodog/SabaiOpen_ARM#3]
test everything with new device

**Comment by PatchyKnowledge** [comment]
- settings from web ui has no effect on system settings (except ones in network/wan)
- openvpn/pptp not working using supplied *.ovpn file/credentials

also, here is current wan settings update process:

1. update sabai settings using $_POST data (www/php/wan.php)
2. update network settings using sabai settings (www/bin/wan.sh)
3. network restart
4. grep+awk stuff from ifconfig/route and update with it network and sabai settings (hotplug.d/60-wanconf)

why we need 4-th step here?
